"""Initial tables creation

Revision ID: d05e91ae1b34
Revises: 
Create Date: 2026-06-27 01:13:08.393592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd05e91ae1b34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('amocrm_tokens', 'access_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.add_column('lead_logs', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('lead_logs', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('lead_logs', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.alter_column('lead_logs', 'amo_lead_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_foreign_key(None, 'lead_logs', 'managers', ['manager_id'], ['id'])
    op.alter_column('managers', 'last_assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_unique_constraint(None, 'managers', ['amo_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'managers', type_='unique') # type: ignore
    op.alter_column('managers', 'last_assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'lead_logs', type_='foreignkey') # type: ignore
    op.alter_column('lead_logs', 'amo_lead_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('lead_logs', 'manager_id')
    op.drop_column('lead_logs', 'status')
    op.drop_column('lead_logs', 'price')
    op.alter_column('amocrm_tokens', 'access_token',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
